name: Using GitHub Secrets by sending an authenticated request
run-name: Make POST request to DummyJSON authenticated endpoint

on:
  workflow_dispatch:

jobs:
  login-user:
    runs-on: ubuntu-24.04

    steps:
      - name: Login to DummyJSON using credentials
        run: |
          TOKEN=$(curl -s https://dummyjson.com/auth/login \
            -H 'Content-Type: application/json' \
            -d '{"username": "${{ secrets.API_USERNAME }}","password": "${{ secrets.API_PASSWORD }}"}' \
            | jq -r '.accessToken')
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV
        shell: bash

      - name: Test authentication endpoint
        run: |
          curl -s https://dummyjson.com/auth/me \
            -H "Authorization: Bearer $TOKEN"
        shell: bash
