name: Using GitHub Secrets by sending an authenticated request
run-name: Make POST request to DummyJSON authenticated endpoint

on:
  workflow_dispatch:

jobs:
  login-user:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Login to DummyJSON using credentials
        env:
          API_USERNAME: ${{ secrets.API_USERNAME }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
        run: |
          TOKEN=$(./.github/scripts/login_avery.sh)
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV
        shell: bash

      - name: Test authentication endpoint
        run: |
          curl -s https://dummyjson.com/auth/me \
            -H "Authorization: Bearer $TOKEN"
        shell: bash
