name: Using GitHub Secrets

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-24.04

    steps:
      - name: Say hello to SECRET
        env:
          NAME: ${{ secrets.MY_SECRET_NAME }}
        run: |
          echo "Hello, $NAME"
      
